// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SampleEntDev.Core.Entities.Schemas;
using SampleEntDev.Repository;
using System;
using System.Collections.Generic;

#nullable disable

namespace SampleEntDev.Repository.Configurations
{
    public partial class ProductFeatureConfiguration : IEntityTypeConfiguration<ProductFeature>
    {
        public void Configure(EntityTypeBuilder<ProductFeature> entity)
        {
            entity.HasKey(e => e.ProductId)
                .HasName("product_feature_pkey");

            entity.ToTable("product_feature", "ecommerce");

            entity.Property(e => e.ProductId)
                .ValueGeneratedNever()
                .HasColumnName("product_id");

            entity.Property(e => e.Color).HasColumnName("color");

            entity.Property(e => e.Height).HasColumnName("height");

            entity.Property(e => e.Width).HasColumnName("width");

            entity.HasOne(d => d.Product)
                .WithOne(p => p.ProductFeature)
                .HasForeignKey<ProductFeature>(d => d.ProductId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("product_feature_product_id_fkey");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ProductFeature> entity);
    }
}
